version: '3.7'      
services:
  activemq:
    image: quay.io/nebulous/activemq-broker:latest
    container_name: activemq
    restart: always
    ports:
        - 6161:61616
    logging:
      driver: "json-file"
      options:
        max-size: "50M"
        max-file: "2" 
    volumes:
        - ./broker/etc/broker.xml:/var/lib/artemis-instance/etc-override/broker.xml
        - ./broker/etc/log4j2.properties:/var/lib/artemis-instance/etc-override/log4j2.properties
        - ./pipeline.json:/pipeline.json
    environment:
        ARTEMIS_MAX_MEMORY: 1024M        
        IOT_PIPELINE_STEPS: "/pipeline.json"
        ACTIVEMQ_ADMIN_PASSWORD: artemis
        
        
  step_a:
    image: ems-nebulous-iot/worker
    build: 
      context: "./worker/${CLIENT_VERSION}"
      dockerfile: ./Dockerfile
    restart: always
    depends_on:
      - activemq
    environment:
      - ${CLIENT_VERSION}_ip=activemq
      - ${CLIENT_VERSION}_port=61616
      - step_name=stepA
      - previous_step_name=src      
      - ${CLIENT_VERSION}_user=artemis
      - ${CLIENT_VERSION}_password=artemis
      
  step_b:
    image: ems-nebulous-iot/worker
    build: 
      context: "./worker/${CLIENT_VERSION}"
      dockerfile: ./Dockerfile
    depends_on:
      - activemq
    restart: always
    environment:
      - ${CLIENT_VERSION}_ip=activemq
      - ${CLIENT_VERSION}_port=61616
      - step_name=stepB
      - previous_step_name=stepA      
      - ${CLIENT_VERSION}_user=artemis
      - ${CLIENT_VERSION}_password=artemis
      
  step_c:
    image: ems-nebulous-iot/worker
    build: 
      context: "./worker/${CLIENT_VERSION}"
      dockerfile: ./Dockerfile
    depends_on:
      - activemq
    restart: always
    environment:
      - ${CLIENT_VERSION}_ip=activemq
      - ${CLIENT_VERSION}_port=61616
      - step_name=stepC
      - previous_step_name=stepB
      - ${CLIENT_VERSION}_user=artemis
      - ${CLIENT_VERSION}_password=artemis
      
      
  step_d:
    image: ems-nebulous-iot/worker
    build: 
      context: "./worker/${CLIENT_VERSION}"
      dockerfile: ./Dockerfile
    depends_on:
      - activemq
    restart: always
    environment:
      - ${CLIENT_VERSION}_ip=activemq
      - ${CLIENT_VERSION}_port=61616
      - step_name=stepD
      - previous_step_name=stepA
      - ${CLIENT_VERSION}_user=artemis
      - ${CLIENT_VERSION}_password=artemis