version: '3.7'      
services:
  activemq:
    image: apache/activemq-artemis:2.37.0-alpine
    container_name: activemq
    restart: always
    ports:
        - 6161:61616
        - 8161:8161 #activemq mgmt ui
        - 6167:61619 #stomp
        - 5672:5672 # amqp
        - 1883:1883 # mqtt
        - 1889:1889 #mqtt WS
    logging:
      driver: "json-file"
      options:
        max-size: "50M"
        max-file: "2" 
    volumes:
        - ./broker/etc:/var/lib/artemis-instance/etc-override
        - ./broker/lib:/var/lib/artemis-instance/lib
    environment:
        ARTEMIS_MAX_MEMORY: 1024M        
        IOT_PIPELINE_STEPS: "{&quot;stepA&quot;: {&quot;inputStream&quot;: &quot;src&quot;,&quot;groupingKeyAccessor&quot;: {&quot;source&quot;:&quot;BODY_JSON&quot;,&quot;expression&quot;: &quot;fieldA&quot;}},&quot;stepB&quot;: {&quot;inputStream&quot;:&quot;stepA&quot;,&quot;groupingKeyAccessor&quot;: {&quot;source&quot;: &quot;BODY_JSON&quot;,&quot;expression&quot;:&quot;fieldB&quot;}},&quot;stepC&quot;: {&quot;inputStream&quot;: &quot;stepB&quot;,&quot;groupingKeyAccessor&quot;:{&quot;source&quot;: &quot;BODY_JSON&quot;,&quot;expression&quot;: &quot;fieldC&quot;}},&quot;stepD&quot;:{&quot;inputStream&quot;: &quot;stepA&quot;,&quot;groupingKeyAccessor&quot;: {&quot;source&quot;: &quot;BODY_JSON&quot;,&quot;expression&quot;: &quot;fieldD&quot;}}}"
        
  step_a:
    image: ems-nebulous-iot/worker
    build: 
      context: "./worker/${CLIENT_VERSION}"
      dockerfile: ./Dockerfile
    restart: always
    depends_on:
      - activemq
    environment:
      - ${CLIENT_VERSION}_ip=activemq
      - ${CLIENT_VERSION}_port=61616
      - step_name=stepA
      - previous_step_name=src      
      - ${CLIENT_VERSION}_user=artemis
      - ${CLIENT_VERSION}_password=artemis
      
  step_b:
    image: ems-nebulous-iot/worker
    build: 
      context: "./worker/${CLIENT_VERSION}"
      dockerfile: ./Dockerfile
    depends_on:
      - activemq
    restart: always
    environment:
      - ${CLIENT_VERSION}_ip=activemq
      - ${CLIENT_VERSION}_port=61616
      - step_name=stepB
      - previous_step_name=stepA      
      - ${CLIENT_VERSION}_user=artemis
      - ${CLIENT_VERSION}_password=artemis
      
  step_c:
    image: ems-nebulous-iot/worker
    build: 
      context: "./worker/${CLIENT_VERSION}"
      dockerfile: ./Dockerfile
    depends_on:
      - activemq
    restart: always
    environment:
      - ${CLIENT_VERSION}_ip=activemq
      - ${CLIENT_VERSION}_port=61616
      - step_name=stepC
      - previous_step_name=stepB
      - ${CLIENT_VERSION}_user=artemis
      - ${CLIENT_VERSION}_password=artemis
      
      
  step_d:
    image: ems-nebulous-iot/worker
    build: 
      context: "./worker/${CLIENT_VERSION}"
      dockerfile: ./Dockerfile
    depends_on:
      - activemq
    restart: always
    environment:
      - ${CLIENT_VERSION}_ip=activemq
      - ${CLIENT_VERSION}_port=61616
      - step_name=stepD
      - previous_step_name=stepA
      - ${CLIENT_VERSION}_user=artemis
      - ${CLIENT_VERSION}_password=artemis