- project:
    check:
      jobs:
        - nebulous-iot-dpp-orchestrator-build-java-libraries
        - nox-linters
    gate:
      jobs:
        - nebulous-iot-dpp-orchestrator-build-java-libraries
        - nox-linters
    promote:
      jobs:
        - nebulous-iot-dpp-orchestrator-upload-java-libraries
